### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by davorpeic** [flipboxfactory/craft-jwt#1]
Hi, 

could you provide some basic _how-to_ this can be used in practice?

thanks

**Comment by nateiler** [comment]
Hi Devor

We're working on getting documentation written against all of our repos.  Until we get there, can you share what you're trying to do and I might be able to provide some quick examples in the mean time.

I can say that right now the JWT plugin is intended to be used for hybrid apps (ex: your web site is calling your own API).

**Comment by davorpeic** [comment]
Hey Nate,
I just found yesterday your awesome guide to implement yii2 REST into craft 3, this library came out in my search for solutions. We are looking into using Craft as a backend for our Nativescript mobile app, so I was looking for ways to auth user and get a jwt token, and you came out :)
